@echo on
REM only runs on WinNT.
set TOOL_PATH=C:\HIGHTEC\toolchains\powerpc\v4.9.3.0\bin\
set OBJ_PATH=C:\Workspace\BMS2202_new\BMS2202_Proj\htc\output\
set LIB_PATH=C:\Workspace\BMS2202_new\BMS2202_Proj\BSWL\_gen\OS\
set LIB_NAME=libCDD_AFE.a
set TOOL_EXE=ppc-vle-ar.exe
set TOOL_ARGS=-rc
set OBJ_LIST=
set OBJ_LIST_01=%OBJ_PATH%\BSWL\CDD\AFE\AFE_9963E\AFE_9963E.o  
set OBJ_LIST_02=%OBJ_PATH%\BSWL\CDD\AFE\AFE_AutosarInterface.o 
set OBJ_LIST_03=%OBJ_PATH%\BSWL\CDD\AFE\Core\AFE_Core.o 
set OBJ_LIST_04=%OBJ_PATH%\BSWL\CDD\AFE\AFE_CoreInterface.o 
set OBJ_LIST_05=%OBJ_PATH%\BSWL\CDD\AFE\ExtDepend\AFE_ExtDep.o 
set OBJ_LIST_06=%OBJ_PATH%\BSWL\CDD\AFE\AFE_9963E\AFE_Results.o 
set OBJ_LIST_07=%OBJ_PATH%\BSWL\CDD\AFE_RT\AFE_rt.o 
set OBJ_LIST_08=%OBJ_PATH%\BSWL\CDD\AFE\AFE_9963E\AFE_StdInterface.o 

DEL /f/s/q %LIB_PATH%%LIB_NAME%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_01%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_02%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_03%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_04%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_05%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_06%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_07%
%TOOL_PATH%%TOOL_EXE% %TOOL_ARGS% %LIB_PATH%%LIB_NAME% %OBJ_LIST_08%

